---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather facts
  hosts: octavia_all
  gather_facts: "{{ gather_facts | default(true) }}"
  tasks:
    - include: "common-tasks/maas_excluded_regex.yml"
    - name: Set the current group
      set_fact:
        maas_current_group: octavia_all
  tags:
    -  maas-openstack-octavia

- name: Install checks for octavia
  hosts: octavia_all
  gather_facts: false
  tasks:
    - name: Install octavia process check
      template:
        src: "templates/rax-maas/octavia_process_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/octavia_process_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Get project id
      shell: ". /root/openrc && openstack project list --user octavia -c ID -f value"
      register: octavia_project_return
      delegate_to: "{{ groups['utility_all'][0] }}"
      tags:
        - skip_ansible_lint

    - name: Set project id
      set_fact:
        octavia_project_id: "{{ octavia_project_return.stdout }}"

    - name: Install octavia quota check
      template:
        src: "templates/rax-maas/octavia_quota_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/octavia_quota_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-octavia

- name: Install checks for openstack octavia-api
  hosts: octavia-api
  gather_facts: false
  tasks:
    - name: Add load-balancer member role
      shell: ". /root/openrc && openstack role add --project $OS_PROJECT_NAME --user $OS_USERNAME load-balancer_observer"
      delegate_to: "{{ groups['utility_all'][0] }}"
      tags:
        - skip_ansible_lint

    - name: Install octavia api checks
      template:
        src: "templates/rax-maas/octavia_api_local_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/octavia_api_local_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install octavia lb checks
      template:
        src: "templates/rax-maas/lb_api_check_octavia.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_octavia.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_remote_check | bool
        - not maas_private_monitoring_enabled

    - name: Install octavia private lb checks
      template:
        src: "templates/rax-maas/private_lb_api_check_octavia.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/private_lb_api_check_octavia.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_private_monitoring_enabled
        - maas_private_monitoring_zone is defined

  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-octavia
